org: saikhanbileg
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        { "Fn::Join": ["", ["arn:aws:s3:::ds21test1", "/*"]] }


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /{routeName}
          method: "*"
